### ISSUE TITLE
Chinese version edits listed below

### ISSUE THREAD

**Issue by HaleliHarel** [macleginn/iclassifier-issues#40]
TOKEN FORM

-When we open an existing token that was already “submitted”  we want to have instead of “submit” a “save” button. 

LEMMA FORM

-For Chinese lemmata, change “transliteration'' into “transcription.” 

-Add a “Hide” to borrowing menu 

REPORTS 

-Add a search box in the lemma, and in the classifier reports.

**Comment by macleginn** [comment]
> TOKEN FORM
> -When we open an existing token that was already “submitted” we want to have instead of “submit” a “save” button.

Fixed for all projects.

**Comment by macleginn** [comment]
> LEMMA FORM
-For Chinese lemmata, change “transliteration'' into “transcription.”
-Add a “Hide” to borrowing menu

Fixed.

**Comment by macleginn** [comment]
> REPORTS
-Add a search box in the lemma, and in the classifier reports.

Done for lemmas.

**Comment by macleginn** [comment]
> REPORTS
-Add a search box in the lemma, and in the classifier reports.

Done.

**Comment by HaleliHarel** [comment]
Thanks, another thing we realized while working with Yanru is that the
dictionary we loaded is not useful. It includes many idioms, so it is quite
impossible to find a single "lemma."
Meanwhile we will add chinese lemmas manually and not from that dictionary.
